# Generated by Django 2.2.5 on 2019-09-15 14:09

from django.db import migrations
import django_enumfield.db.fields
import logix.enums.argument_set


class Migration(migrations.Migration):

    dependencies = [
        ('logix', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='argument',
            name='argument_set',
            field=django_enumfield.db.fields.EnumField(default=0, enum=logix.enums.argument_set.ArgumentSet),
        ),
    ]
